<?xml version="1.0" encoding="UTF-8" ?>                                                                            
<!DOCTYPE uri-list [                                                                                               
<!ELEMENT uri-list (uri)+ >                                                                                        
<!ELEMENT uri (request, document) >                                                                                
<!ELEMENT request (#PCDATA) >                                                                                      
<!ELEMENT document (#PCDATA) >                                                                                     
]>                                                                                                                 
<uri-list>                                                                                                         
 <!-- begin CSAF Common Vulnerability Reporting Framework (CVRF) Version 1.2 -->                                                                   
<uri>                                                                                                              
  <request>/ns/csaf-cvrf/v1.2/common</request>                                                                           
  <document>/csaf-cvrf/v1.2/cs01/csaf-cvrf-v1.2-namespace.html</document>            
</uri>                                                                                                             

<uri>                                                                                                              
  <request>/ns/csaf-cvrf/v1.2/cvrf</request>                                                                           
  <document>/csaf-cvrf/v1.2/cs01/csaf-cvrf-v1.2-namespace.html</document>            
</uri>                                                                                                             
                                  
<uri>                                                                                                              
  <request>/ns/csaf-cvrf/v1.2/prod</request>                                                                           
  <document>/csaf-cvrf/v1.2/cs01/csaf-cvrf-v1.2-namespace.html</document>            
</uri>                                                                                                             

<uri>                                                                                                              
  <request>/ns/csaf-cvrf/v1.2/vuln</request>                                                                           
  <document>/csaf-cvrf/v1.2/cs01/csaf-cvrf-v1.2-namespace.html</document>            
</uri>
<!-- end CSAF Common Vulnerability Reporting Framework (CVRF) Version 1.2 -->                                                                   
                                                                                                            
                                                                                                                                                                                                                                                                                                                       
</uri-list> 